# Generated by Django 3.0.5 on 2021-04-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
        ),
    ]
